FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app
EXPOSE 80

# copy all .csproj files and restore as distinct layers.   Use of the same COPY command
# for every dockerfile in the project to take advantage of docker caching
COPY eCarAuction.sln eCarAuction.sln
COPY src/CarAuctionService/CarAuctionService.csproj src/CarAuctionService/CarAuctionService.csproj
COPY src/SearchAuctionService/SearchAuctionService.csproj src/SearchAuctionService/SearchAuctionService.csproj
COPY src/Contracts/Contracts.csproj src/Contracts/Contracts.csproj
COPY src/GatewayService/GatewayService.csproj src/GatewayService/GatewayService.csproj
COPY src/IdentityService/IdentityService.csproj src/IdentityService/IdentityService.csproj

# Restore package deps
RUN dotnet restore eCarAuction.sln

# Copy the app folders over
COPY src/SearchAuctionService src/SearchAuctionService
COPY src/Contracts src/Contracts
WORKDIR /app/src/SearchAuctionService
RUN dotnet publish -c Release -o /app/src/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app/src/out .
ENTRYPOINT [ "dotnet", "SearchAuctionService.dll" ]