services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: carauctions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa$w0rd
    ports:
      - 5432:5432
    expose:
      - "5435"
    volumes:
      - /var/lib/postresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data



