services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: carauctions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa
    ports:
      - 5432:5432
    expose:
      - "5435"
    volumes:
      - /var/lib/postresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: carauctionapp/auction-svc:latest
    build: 
      context: .
      dockerfile: src/CarAuctionService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_URLS=http://+:7777
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=Pa;Database=carauctions
        - IdentityServiceUrl=http://identity-svc
        - Kestrel__Endpoints__Grpc__Protocols=Http2
        - Kestrel__Endpoints__Grpc__Url=http://+:7777
        - Kestrel__Endpoints__WebApi__Protocols=Http1
        - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 5001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: carauctionapp/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchAuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongo123@mongodb
      - CarAuctionService=http://auction-svc/
    ports:
      - 6001:80
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: carauctionapp/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=Pa;Database=Identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: carauctionapp/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 7001:80
  
  



